language: cpp
sudo: required

notifications:
  email: false

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - mkdir bin
  - cd build
  - cmake ..

script:
  - pwd
  - make
  - ../bin/RobotTest
