language: cpp
sudo: required

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

notifications:
  email: false

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - mkdir bin
  - cd build
  - cmake ..

script:
  - pwd
  - make
  - ../bin/RobotTest
